#
# The standard Pebble SDK build script. `pebble build` runs this.
#

top = "."
out = "build"


def options(ctx):
    ctx.load("pebble_sdk")


def configure(ctx):
    ctx.load("pebble_sdk")


def build(ctx):
    ctx.load("pebble_sdk")

    binaries = []
    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.set_env(ctx.all_envs[platform])
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf = "{}/pebble-app.elf".format(ctx.env.BUILD_DIR)
        ctx.pbl_build(
            source=ctx.path.ant_glob("src/c/**/*.c"),
            target=app_elf,
            bin_type="app",
        )
        binaries.append({"platform": platform, "app_elf": app_elf})

    ctx.set_group("bundle")
    ctx.pbl_bundle(
        binaries=binaries,
        js=ctx.path.ant_glob(["src/pkjs/**/*.js", "src/pkjs/**/*.json"]),
        js_entry_file="src/pkjs/index.js",
    )
